---
- name: INSTALL NGINX WEB SERVER
  hosts: all
  gather_facts: false

  vars:
     tower_hosts_server: all


  tasks:
    - include_role:
         name: nginx_install
      when: server_os == 'linux'

   


      
    

    

  
    
